# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArticlesOfflineListDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArticlesOfflineListDemo
  pod 'SDWebImageSwiftUI'

  target 'ArticlesOfflineListDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArticlesOfflineListDemoUITests' do
    # Pods for testing
  end

end
